version: '3'

services:
 postfix-mailgun-relay:
  build: .
  image: "ralfherzog/docker-postfix-mailgun-relay"
  container_name: "postfix-mailgun-relay"
  environment:
   SYSTEM_TIMEZONE: "Europe/Berlin"
   MYNETWORKS: "10.0.0.0/8 172.0.0.0/8 192.168.0.0/16"
   EMAIL: "postmaster@mg.{YOURDOMAIN}"
   EMAILPASS: "{PASSWORD}"
  ports:
  - "9025:25"
