version: '3'

services:
 postfix-mailgun-relay:
  build: .
  image: "ralfherzog/docker-postfix-mailgun-relay"
  container_name: "postfix-mailgun-relay"
  environment:
   SYSTEM_TIMEZONE: "Europe/Berlin"
   MYNETWORKS: ""
   EMAIL: "postmaster@mg.example.com"
   EMAILPASS: "supersecretpassword"
   DOMAIN: "example.com"
   SASL_LDAP_SERVER: 'ldap.example.com'
   SASL_LDAP_BIND_DN: 'cn=smtp,ou=services,dc=example,dc=com'
   SASL_LDAP_BIND_DN_PASSWORD: 'ldapsmtppassword'
   SASL_LDAP_USERS: 'ou=users,dc=example,dc=com'
   SASL_LDAP_USERS_FILTER: '(&(objectclass=inetOrgPerson)(mail=%u))'
  ports:
  - "9025:25"